"""Add table for debit cards and readd type to payment table.

Revision ID: 09f0bbd597ea
Revises: 99f0a00585be
Create Date: 2022-01-07 12:03:11.453778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f0bbd597ea'
down_revision = '99f0a00585be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'debit_card',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('card_number', sa.String(length=22), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('card_number')
    )
    op.add_column('payment', sa.Column('card_number', sa.String(length=22), nullable=True))
    op.add_column('payment', sa.Column('type', sa.String(length=20), nullable=True))
    op.create_foreign_key("payment_debit_card_fkey", 'payment', 'debit_card', ['card_number'], ['card_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("payment_debit_card_fkey", 'payment', type_='foreignkey')
    op.drop_column('payment', 'type')
    op.drop_column('payment', 'card_number')
    op.drop_table('debit_card')
    # ### end Alembic commands ###
