"""Increased character limits for certain fields in payment.

Revision ID: 0cf9ae1295b9
Revises: 8b1b83a3da7d
Create Date: 2023-02-15 06:33:50.621572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf9ae1295b9'
down_revision = '8b1b83a3da7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'creditor_account',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('payment', 'debtor_account',
               existing_type=sa.VARCHAR(length=22),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('payment', 'end_to_end_id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('payment', 'entry_reference',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'entry_reference',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('payment', 'end_to_end_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('payment', 'debtor_account',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=22),
               existing_nullable=True)
    op.alter_column('payment', 'creditor_account',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=22),
               existing_nullable=True)
    # ### end Alembic commands ###
