"""Removed iban name because we won't need it for BNG.

Revision ID: 0ffa4b4020d6
Revises: 0f0fca946d89
Create Date: 2021-12-15 14:32:01.756793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffa4b4020d6'
down_revision = '0f0fca946d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('IBAN', 'iban_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('IBAN', sa.Column('iban_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
