"""Added a field 'finished_description' for the description that has to be entered when a subproject is finished.

Revision ID: 221c0e6cc44e
Revises: 78f950d2f17f
Create Date: 2022-05-19 11:42:42.192206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221c0e6cc44e'
down_revision = '78f950d2f17f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subproject', sa.Column('finished_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subproject', 'finished_description')
    # ### end Alembic commands ###
