"""Justified field should be on funder, not project.

Revision ID: 233a4bd6cd00
Revises: 221c0e6cc44e
Create Date: 2022-05-20 08:52:36.366711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233a4bd6cd00'
down_revision = '221c0e6cc44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funder', sa.Column('justified', sa.Boolean(), nullable=True))
    op.drop_column('project', 'justified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('justified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('funder', 'justified')
    # ### end Alembic commands ###
