"""Added a many to many relationship between funder and subproject.

Revision ID: 3532f51762c4
Revises: b364af45763c
Create Date: 2022-05-05 15:11:52.378182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3532f51762c4'
down_revision = 'b364af45763c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subproject_funder',
    sa.Column('subproject_id', sa.Integer(), nullable=False),
    sa.Column('funder_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funder_id'], ['funder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subproject_id'], ['subproject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subproject_id', 'funder_id')
    )
    op.drop_constraint('funder_subproject_fkey', 'funder', type_='foreignkey')
    op.drop_column('funder', 'subproject_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funder', sa.Column('subproject_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('funder_subproject_fkey', 'funder', 'subproject', ['subproject_id'], ['id'], ondelete='CASCADE')
    op.drop_table('subproject_funder')
    # ### end Alembic commands ###
