"""Enabled profile images for projects and subprojects.

Revision ID: 4552f8ac8df9
Revises: 3532f51762c4
Create Date: 2022-05-10 09:32:39.632154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4552f8ac8df9"
down_revision = "3532f51762c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("image", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "project_file_fkey", "project", "file", ["image"], ["id"], ondelete="SET NULL"
    )
    op.add_column("subproject", sa.Column("image", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "subproject_file_fkey",
        "subproject",
        "file",
        ["image"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subproject_file_fkey", "subproject", type_="foreignkey")
    op.drop_column("subproject", "image")
    op.drop_constraint("project_file_fkey", "project", type_="foreignkey")
    op.drop_column("project", "image")
    # ### end Alembic commands ###
