"""KvK doesn't have to be unique.

Revision ID: 4d6736615bf3
Revises: 12aed8481bf5
Create Date: 2022-05-23 11:03:59.922138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6736615bf3'
down_revision = '12aed8481bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_registration_kvk_key', 'project', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_registration_kvk_key', 'project', ['registration_kvk'])
    # ### end Alembic commands ###
