"""Added a debit card table with relationships to payments and projects.

Revision ID: 4ff06d3a0173
Revises: 99f0a00585be
Create Date: 2021-12-29 13:46:06.355936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff06d3a0173'
down_revision = '99f0a00585be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debit_card',
    sa.Column('card_number', sa.String(length=22), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.add_column('payment', sa.Column('card_number', sa.String(length=22), nullable=True))
    op.create_foreign_key(None, 'payment', 'debit_card', ['card_number'], ['card_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'card_number')
    op.drop_table('debit_card')
    # ### end Alembic commands ###
