"""Removed fields in project that are no longer used.

Revision ID: 78f950d2f17f
Revises: 33c7a1ecf88f
Create Date: 2022-05-17 12:30:53.560092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f950d2f17f'
down_revision = '33c7a1ecf88f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_IBAN_iban', table_name='IBAN')
    op.drop_table('IBAN')
    op.drop_index('ix_project_bank_name', table_name='project')
    op.drop_index('ix_project_iban', table_name='project')
    op.drop_index('ix_project_iban_name', table_name='project')
    op.drop_column('project', 'bunq_access_token')
    op.drop_column('project', 'iban')
    op.drop_column('project', 'bank_name')
    op.drop_column('project', 'iban_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('iban_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('bank_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('iban', sa.VARCHAR(length=34), autoincrement=False, nullable=True))
    op.add_column('project', sa.Column('bunq_access_token', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_project_iban_name', 'project', ['iban_name'], unique=False)
    op.create_index('ix_project_iban', 'project', ['iban'], unique=True)
    op.create_index('ix_project_bank_name', 'project', ['bank_name'], unique=False)
    op.create_table('IBAN',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"IBAN_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('iban', sa.VARCHAR(length=34), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='IBAN_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='IBAN_pkey')
    )
    op.create_index('ix_IBAN_iban', 'IBAN', ['iban'], unique=False)
    # ### end Alembic commands ###
