"""Added new columns to project model for verantwoordingsmodule.

Revision ID: 86092566a210
Revises: 4d1524065b42
Create Date: 2022-05-05 11:25:33.379308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86092566a210"
down_revision = "4d1524065b42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("address_applicant", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "project", sa.Column("legal_entity", sa.String(length=20), nullable=True)
    )
    op.add_column("project", sa.Column("owner", sa.String(length=120), nullable=True))
    op.add_column(
        "project", sa.Column("owner_email", sa.String(length=120), nullable=True)
    )
    op.add_column(
        "project", sa.Column("project_location", sa.String(length=120), nullable=True)
    )
    op.add_column("project", sa.Column("purpose", sa.Text(), nullable=True))
    op.add_column(
        "project", sa.Column("registration_kvk", sa.String(length=120), nullable=True)
    )
    op.add_column("project", sa.Column("target_audience", sa.Text(), nullable=True))
    op.create_unique_constraint(
        "project_registration_kvk_key", "project", ["registration_kvk"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_registration_kvk_key", "project", type_="unique")
    op.drop_column("project", "target_audience")
    op.drop_column("project", "registration_kvk")
    op.drop_column("project", "purpose")
    op.drop_column("project", "project_location")
    op.drop_column("project", "owner_email")
    op.drop_column("project", "owner")
    op.drop_column("project", "legal_entity")
    op.drop_column("project", "address_applicant")
    # ### end Alembic commands ###
