"""Removed debit card table completely, because Alembic does not automatically pick up primary key changes in an already existing table.

Revision ID: 99f0a00585be
Revises: b76d3b1f1639
Create Date: 2021-12-29 13:44:20.294903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f0a00585be'
down_revision = 'b76d3b1f1639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debit_card')
    op.drop_column('payment', 'card_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('card_number', sa.VARCHAR(length=22), autoincrement=False, nullable=True))
    op.create_table('debit_card',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('iban', sa.VARCHAR(length=34), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['iban'], ['subproject.iban'], name='debit_card_iban_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='debit_card_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='debit_card_pkey')
    )
    # ### end Alembic commands ###
