"""Projects now need to use subprojects. So removed the contains_subprojects flag and categories relationship from Project. Categories can now only be made for subprojects, so removed project_id as a foreign key.

Revision ID: a37c583d560b
Revises: ddbc513d910c
Create Date: 2022-05-29 18:38:59.195639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37c583d560b'
down_revision = 'ddbc513d910c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_project_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'project_id')
    op.drop_column('project', 'contains_subprojects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('contains_subprojects', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('category', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_project_id_fkey', 'category', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
