"""Added new fields to subproject model.

Revision ID: b364af45763c
Revises: 5a724787dd53
Create Date: 2022-05-05 14:31:05.353132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b364af45763c'
down_revision = '5a724787dd53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subproject', sa.Column('purpose', sa.Text(), nullable=True))
    op.add_column('subproject', sa.Column('target_audience', sa.Text(), nullable=True))
    op.drop_index('ix_subproject_iban', table_name='subproject')
    op.drop_index('ix_subproject_iban_name', table_name='subproject')
    op.drop_column('subproject', 'iban_name')
    op.drop_column('subproject', 'iban')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subproject', sa.Column('iban', sa.VARCHAR(length=34), autoincrement=False, nullable=True))
    op.add_column('subproject', sa.Column('iban_name', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_subproject_iban_name', 'subproject', ['iban_name'], unique=False)
    op.create_index('ix_subproject_iban', 'subproject', ['iban'], unique=True)
    op.drop_column('subproject', 'target_audience')
    op.drop_column('subproject', 'purpose')
    # ### end Alembic commands ###
