"""Now using download for getting payments. The fields are different for this data, so I had to adjust the schema of the payment table.

Revision ID: b3d56718c251
Revises: 2f99adfebc22
Create Date: 2021-12-20 14:22:03.538463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d56718c251'
down_revision = '2f99adfebc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('creditor_account', sa.String(length=22), nullable=True))
    op.add_column('payment', sa.Column('debtor_account', sa.String(length=22), nullable=True))
    op.drop_column('payment', 'creditor_account_currency')
    op.drop_column('payment', 'creditor_account_iban')
    op.drop_column('payment', 'transaction_currency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('transaction_currency', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('creditor_account_iban', sa.VARCHAR(length=22), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('creditor_account_currency', sa.VARCHAR(length=8), autoincrement=False, nullable=True))
    op.drop_column('payment', 'debtor_account')
    op.drop_column('payment', 'creditor_account')
    # ### end Alembic commands ###
