"""Added a field for the card number in payment. We will use this field to link payments to projects.

Revision ID: b76d3b1f1639
Revises: 0bbc39e7fc80
Create Date: 2021-12-29 11:25:23.795695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76d3b1f1639'
down_revision = '0bbc39e7fc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('card_number', sa.String(length=22), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'card_number')
    # ### end Alembic commands ###
