"""Added a column for keeping track of the last used project of a debit card.

Revision ID: bc62655078f7
Revises: 09f0bbd597ea
Create Date: 2022-01-08 20:47:29.180495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc62655078f7'
down_revision = '09f0bbd597ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit_card', sa.Column('last_used_project_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debit_card', 'last_used_project_id')
    # ### end Alembic commands ###
