"""Added a column for keeping track of the datetime of the last succesful payment import.

Revision ID: ca3a96be6abf
Revises: bc62655078f7
Create Date: 2022-01-10 12:53:52.650091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3a96be6abf'
down_revision = 'bc62655078f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bng_account', sa.Column('last_import_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bng_account', 'last_import_on')
    # ### end Alembic commands ###
