"""Added a field for the project's budget file.

Revision ID: ddbc513d910c
Revises: 4d6736615bf3
Create Date: 2022-05-29 11:21:37.954817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddbc513d910c"
down_revision = "4d6736615bf3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("budget_file", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "project_budget_file_fkey",
        "project",
        "file",
        ["budget_file"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("project_budget_file_fkey", "project", type_="foreignkey")
    op.drop_column("project", "budget_file")
    # ### end Alembic commands ###
