"""Added the type field for the payment model again. Need it for backwards compatibility.

Revision ID: e61170431e33
Revises: ecde3fafc03a
Create Date: 2021-12-31 12:21:02.896288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61170431e33'
down_revision = 'ecde3fafc03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'type')
    # ### end Alembic commands ###
