"""Debit cards should not be removed when a project that is linked is removed, because they are a foreign key for payments.

Revision ID: ecde3fafc03a
Revises: 4ff06d3a0173
Create Date: 2021-12-30 15:18:38.390443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecde3fafc03a'
down_revision = '4ff06d3a0173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('debit_card_project_id_fkey', 'debit_card', type_='foreignkey')
    op.create_foreign_key(None, 'debit_card', 'project', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'debit_card', type_='foreignkey')
    op.create_foreign_key('debit_card_project_id_fkey', 'debit_card', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
