"""Added a table for BNG accounts.

Revision ID: f448a03d2d85
Revises: 0ffa4b4020d6
Create Date: 2021-12-16 11:18:23.573614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f448a03d2d85'
down_revision = '0ffa4b4020d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bng_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('consent_id', sa.String(length=36), nullable=True),
    sa.Column('access_token', sa.String(length=496), nullable=True),
    sa.Column('expires_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bng_account')
    # ### end Alembic commands ###
